// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuantityMeasurementAppRepositories.Context;

#nullable disable

namespace QuantityMeasurementAppRepositories.Migrations
{
    [DbContext(typeof(DatabaseAppContext))]
    partial class DatabaseAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuantityMeasurementAppModels.Entities.QuantityEntity", b =>
                {
                    b.Property<long>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EntityId"));

                    b.Property<DateTime>("EntityCreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("entity_created_at");

                    b.Property<string>("EntityErrorMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("entity_error_message");

                    b.Property<string>("EntityFirstUnit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("entity_first_unit");

                    b.Property<double>("EntityFirstValue")
                        .HasColumnType("float")
                        .HasColumnName("entity_first_value");

                    b.Property<string>("EntityMeasurementType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("entity_measurement_type");

                    b.Property<string>("EntityOperation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("entity_operation");

                    b.Property<double>("EntityResultValue")
                        .HasColumnType("float")
                        .HasColumnName("entity_result_value");

                    b.Property<string>("EntitySecondUnit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("entity_second_unit");

                    b.Property<double>("EntitySecondValue")
                        .HasColumnType("float")
                        .HasColumnName("entity_second_value");

                    b.Property<DateTime>("EntityUpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("entity_updated_at");

                    b.Property<bool>("IsEntityError")
                        .HasColumnType("bit")
                        .HasColumnName("entity_is_error");

                    b.HasKey("EntityId");

                    b.ToTable("quantity_measurements_tables_conversion");
                });
#pragma warning restore 612, 618
        }
    }
}
